/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:20:29 GMT 2019
 */

package org.apache.commons.math4.ml.distance;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.ml.distance.EarthMoversDistance;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EarthMoversDistance_ESTest extends EarthMoversDistance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EarthMoversDistance earthMoversDistance0 = new EarthMoversDistance();
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = (-3250.999245009);
      double double0 = earthMoversDistance0.compute(doubleArray0, doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EarthMoversDistance earthMoversDistance0 = new EarthMoversDistance();
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = (-3250.999245009);
      double[] doubleArray1 = new double[2];
      double double0 = earthMoversDistance0.compute(doubleArray0, doubleArray1);
      assertEquals(6501.998490018, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EarthMoversDistance earthMoversDistance0 = new EarthMoversDistance();
      double[] doubleArray0 = new double[9];
      double[] doubleArray1 = new double[4];
      try { 
        earthMoversDistance0.compute(doubleArray0, doubleArray1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 9 != 4
         //
         verifyException("org.apache.commons.math4.util.MathArrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EarthMoversDistance earthMoversDistance0 = new EarthMoversDistance();
      double[] doubleArray0 = new double[9];
      // Undeclared exception!
      try { 
        earthMoversDistance0.compute(doubleArray0, (double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.MathArrays", e);
      }
  }
}
