/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:53:36 GMT 2019
 */

package org.apache.commons.math4.analysis.interpolation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.analysis.interpolation.BicubicFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class BicubicFunction_ESTest extends BicubicFunction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double[] doubleArray0 = new double[21];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      double double0 = bicubicFunction0.value(0.8534190401770204, 0.8534190401770204);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double[] doubleArray0 = new double[21];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      double double0 = bicubicFunction0.value(1.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double[] doubleArray0 = new double[17];
      doubleArray0[0] = 3411.28;
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      double double0 = bicubicFunction0.value(0.0, 0.0);
      assertEquals(3411.28, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BicubicFunction bicubicFunction0 = null;
      try {
        bicubicFunction0 = new BicubicFunction((double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.analysis.interpolation.BicubicFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      double[] doubleArray0 = new double[15];
      BicubicFunction bicubicFunction0 = null;
      try {
        bicubicFunction0 = new BicubicFunction(doubleArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 15
         //
         verifyException("org.apache.commons.math4.analysis.interpolation.BicubicFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      double[] doubleArray0 = new double[20];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      // Undeclared exception!
      try { 
        bicubicFunction0.value(0.0, (-967.4750160721165));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -967.475 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.analysis.interpolation.BicubicFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      double[] doubleArray0 = new double[21];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      // Undeclared exception!
      try { 
        bicubicFunction0.value(2944.200808749, 0.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 2,944.201 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.analysis.interpolation.BicubicFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      double[] doubleArray0 = new double[26];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      double double0 = bicubicFunction0.value(0.0, 1.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      double[] doubleArray0 = new double[20];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      // Undeclared exception!
      try { 
        bicubicFunction0.value((-829.6487431517725), (-829.6487431517725));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -829.649 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.analysis.interpolation.BicubicFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      double[] doubleArray0 = new double[17];
      BicubicFunction bicubicFunction0 = new BicubicFunction(doubleArray0);
      // Undeclared exception!
      try { 
        bicubicFunction0.value(0.0, 1226.333417666);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 1,226.333 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.analysis.interpolation.BicubicFunction", e);
      }
  }
}
