/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:55:24 GMT 2019
 */

package org.apache.commons.math4.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math4.exception.NoBracketingException;
import org.apache.commons.math4.exception.util.Localizable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoBracketingException_ESTest extends NoBracketingException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(0.0, 0.0, 0.0, (-2685.0));
      double double0 = noBracketingException0.getLo();
      assertEquals(0.0, noBracketingException0.getHi(), 0.01);
      assertEquals((-2685.0), noBracketingException0.getFHi(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, noBracketingException0.getFLo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException((-1802.651347), (-1802.651347), Double.POSITIVE_INFINITY, (-2273.8223459843));
      double double0 = noBracketingException0.getLo();
      assertEquals(Double.POSITIVE_INFINITY, noBracketingException0.getFLo(), 0.01);
      assertEquals((-2273.8223459843), noBracketingException0.getFHi(), 0.01);
      assertEquals((-1802.651347), noBracketingException0.getHi(), 0.01);
      assertEquals((-1802.651347), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(824.83, 0.0, 0.0, 824.83);
      double double0 = noBracketingException0.getHi();
      assertEquals(824.83, noBracketingException0.getLo(), 0.01);
      assertEquals(824.83, noBracketingException0.getFHi(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, noBracketingException0.getFLo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(0.0, 0.0, 0.0, 0.0);
      double double0 = noBracketingException0.getFLo();
      assertEquals(0.0, noBracketingException0.getHi(), 0.01);
      assertEquals(0.0, noBracketingException0.getLo(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, noBracketingException0.getFHi(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(Double.NaN, Double.NaN, (-3602.9), 639.5808192361835);
      double double0 = noBracketingException0.getFLo();
      assertEquals(639.5808192361835, noBracketingException0.getFHi(), 0.01);
      assertEquals((-3602.9), double0, 0.01);
      assertEquals(Double.NaN, noBracketingException0.getLo(), 0.01);
      assertEquals(Double.NaN, noBracketingException0.getHi(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(0.0, 0.0, 0.0, 0.0);
      double double0 = noBracketingException0.getFHi();
      assertEquals(0.0, noBracketingException0.getLo(), 0.01);
      assertEquals(0.0, noBracketingException0.getHi(), 0.01);
      assertEquals(0.0, noBracketingException0.getFLo(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(0.0, 0.9999, 233.661977801, (-643.551));
      double double0 = noBracketingException0.getFHi();
      assertEquals(233.661977801, noBracketingException0.getFLo(), 0.01);
      assertEquals(0.9999, noBracketingException0.getHi(), 0.01);
      assertEquals(0.0, noBracketingException0.getLo(), 0.01);
      assertEquals((-643.551), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException((Localizable) null, (-316.79446044), (-316.79446044), 1.0, (-1.0), (Object[]) null);
      double double0 = noBracketingException0.getHi();
      assertEquals(1.0, noBracketingException0.getFLo(), 0.01);
      assertEquals((-316.79446044), double0, 0.01);
      assertEquals((-1.0), noBracketingException0.getFHi(), 0.01);
      assertEquals((-316.79446044), noBracketingException0.getLo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(1270.4131847061924, 1270.4131847061924, 1270.4131847061924, 1270.4131847061924);
      double double0 = noBracketingException0.getFLo();
      assertEquals(1270.4131847061924, noBracketingException0.getFHi(), 0.01);
      assertEquals(1270.4131847061924, double0, 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getLo(), 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getHi(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(1270.4131847061924, 1270.4131847061924, 1270.4131847061924, 1270.4131847061924);
      double double0 = noBracketingException0.getHi();
      assertEquals(1270.4131847061924, noBracketingException0.getFHi(), 0.01);
      assertEquals(1270.4131847061924, double0, 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getFLo(), 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getLo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(1270.4131847061924, 1270.4131847061924, 1270.4131847061924, 1270.4131847061924);
      double double0 = noBracketingException0.getLo();
      assertEquals(1270.4131847061924, noBracketingException0.getFLo(), 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getHi(), 0.01);
      assertEquals(1270.4131847061924, double0, 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getFHi(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      NoBracketingException noBracketingException0 = new NoBracketingException(1270.4131847061924, 1270.4131847061924, 1270.4131847061924, 1270.4131847061924);
      double double0 = noBracketingException0.getFHi();
      assertEquals(1270.4131847061924, double0, 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getFLo(), 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getHi(), 0.01);
      assertEquals(1270.4131847061924, noBracketingException0.getLo(), 0.01);
  }
}
