/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:31:05 GMT 2019
 */

package org.apache.commons.math4.analysis.solvers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.analysis.polynomials.PolynomialFunction;
import org.apache.commons.math4.analysis.solvers.LaguerreSolver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractPolynomialSolver_ESTest extends AbstractPolynomialSolver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LaguerreSolver laguerreSolver0 = new LaguerreSolver((-2367.1004542351593));
      PolynomialFunction polynomialFunction0 = mock(PolynomialFunction.class, new ViolatedAssumptionAnswer());
      doReturn((double[]) null).when(polynomialFunction0).getCoefficients();
      laguerreSolver0.setup(0, polynomialFunction0, (-2367.1004542351593), (-2367.1004542351593), 0);
      laguerreSolver0.getCoefficients();
      assertEquals((-2367.1004542351593), laguerreSolver0.getMin(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LaguerreSolver laguerreSolver0 = new LaguerreSolver(1.0);
      double[] doubleArray0 = new double[4];
      laguerreSolver0.solveComplex(doubleArray0, 0.0);
      laguerreSolver0.getCoefficients();
      assertEquals(Double.POSITIVE_INFINITY, laguerreSolver0.getMax(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LaguerreSolver laguerreSolver0 = new LaguerreSolver(2547.273, 3096.6580501605717);
      // Undeclared exception!
      try { 
        laguerreSolver0.setup(1, (PolynomialFunction) null, 3096.6580501605717, 2547.273, 3096.6580501605717);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LaguerreSolver laguerreSolver0 = new LaguerreSolver(0.0, 0.0, 0.0);
      // Undeclared exception!
      try { 
        laguerreSolver0.getCoefficients();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.AbstractPolynomialSolver", e);
      }
  }
}
