/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 22:03:06 GMT 2019
 */

package org.apache.commons.math4.analysis.integration.gauss;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.analysis.integration.gauss.LaguerreRuleFactory;
import org.apache.commons.math4.util.Pair;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class LaguerreRuleFactory_ESTest extends LaguerreRuleFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      int int0 = Integer.MAX_VALUE;
      // Undeclared exception!
      laguerreRuleFactory0.computeRule(Integer.MAX_VALUE);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      // Undeclared exception!
      laguerreRuleFactory0.computeRule(1048);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      // Undeclared exception!
      try { 
        laguerreRuleFactory0.computeRule(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math4.linear.AbstractRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      Pair<Double[], Double[]> pair0 = laguerreRuleFactory0.computeRule(11);
      laguerreRuleFactory0.addRule(pair0);
      laguerreRuleFactory0.computeRule(11);
      laguerreRuleFactory0.computeRule(11);
      laguerreRuleFactory0.getRuleInternal(11);
      // Undeclared exception!
      laguerreRuleFactory0.computeRule(1572);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      int int0 = 2;
      laguerreRuleFactory0.getRule(2);
      laguerreRuleFactory0.computeRule(2);
      int int1 = 27;
      laguerreRuleFactory0.computeRule(2);
      // Undeclared exception!
      laguerreRuleFactory0.computeRule(27);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      int int0 = 943;
      // Undeclared exception!
      laguerreRuleFactory0.computeRule(943);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LaguerreRuleFactory laguerreRuleFactory0 = new LaguerreRuleFactory();
      int int0 = 2;
      laguerreRuleFactory0.getRule(2);
      // Undeclared exception!
      try { 
        laguerreRuleFactory0.computeRule(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math4.linear.AbstractRealMatrix", e);
      }
  }
}
