/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 22:03:22 GMT 2019
 */

package org.apache.commons.math4.linear;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.linear.ConjugateGradient;
import org.apache.commons.math4.linear.IterativeLinearSolver;
import org.apache.commons.math4.linear.RealLinearOperator;
import org.apache.commons.math4.linear.RealVector;
import org.apache.commons.math4.linear.SymmLQ;
import org.apache.commons.math4.util.IterationManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IterativeLinearSolver_ESTest extends IterativeLinearSolver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IterationManager iterationManager0 = mock(IterationManager.class, new ViolatedAssumptionAnswer());
      SymmLQ symmLQ0 = new SymmLQ(iterationManager0, 12.0, false);
      RealLinearOperator realLinearOperator0 = mock(RealLinearOperator.class, new ViolatedAssumptionAnswer());
      try { 
        symmLQ0.solveInPlace(realLinearOperator0, (RealVector) null, (RealVector) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConjugateGradient conjugateGradient0 = new ConjugateGradient(3096, (-1107.47375651), false);
      RealLinearOperator realLinearOperator0 = mock(RealLinearOperator.class, new ViolatedAssumptionAnswer());
      try { 
        conjugateGradient0.solve(realLinearOperator0, (RealVector) null, (RealVector) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IterationManager iterationManager0 = mock(IterationManager.class, new ViolatedAssumptionAnswer());
      SymmLQ symmLQ0 = new SymmLQ(iterationManager0, (-1.0), true);
      RealLinearOperator realLinearOperator0 = mock(RealLinearOperator.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(realLinearOperator0).getColumnDimension();
      try { 
        symmLQ0.solve(realLinearOperator0, (RealVector) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RealLinearOperator realLinearOperator0 = mock(RealLinearOperator.class, new ViolatedAssumptionAnswer());
      try { 
        IterativeLinearSolver.checkParameters(realLinearOperator0, (RealVector) null, (RealVector) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConjugateGradient conjugateGradient0 = new ConjugateGradient(29, 29, true);
      IterationManager iterationManager0 = conjugateGradient0.getIterationManager();
      assertNotNull(iterationManager0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IterationManager iterationManager0 = mock(IterationManager.class, new ViolatedAssumptionAnswer());
      SymmLQ symmLQ0 = new SymmLQ(iterationManager0, (-1.0), true);
      RealLinearOperator realLinearOperator0 = mock(RealLinearOperator.class, new ViolatedAssumptionAnswer());
      doReturn((-191)).when(realLinearOperator0).getColumnDimension();
      // Undeclared exception!
      try { 
        symmLQ0.solve(realLinearOperator0, (RealVector) null);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.linear.ArrayRealVector", e);
      }
  }
}
