/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Dec 11 22:30:36 GMT 2019
 */

package org.apache.commons.math4.optim;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class BaseOptimizer_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.math4.optim.BaseOptimizer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "ANSI_X3.4-1968"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/projects/commons-math"); 
    java.lang.System.setProperty("user.home", "/root"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "root"); 
    java.lang.System.setProperty("user.timezone", "Etc/UTC"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BaseOptimizer_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.rng.core.BaseProvider",
      "org.apache.commons.math4.util.FastMath",
      "org.apache.commons.math4.optim.univariate.BrentOptimizer",
      "org.apache.commons.rng.RandomProviderState",
      "org.apache.commons.math4.exception.MathArithmeticException",
      "org.apache.commons.math4.exception.MathIllegalStateException",
      "org.apache.commons.math4.exception.NumberIsTooSmallException",
      "org.apache.commons.math4.optim.univariate.MultiStartUnivariateOptimizer",
      "org.apache.commons.math4.util.Pair",
      "org.apache.commons.math4.analysis.UnivariateFunction",
      "org.apache.commons.math4.exception.util.Localizable",
      "org.apache.commons.math4.optim.linear.PivotSelectionRule",
      "org.apache.commons.math4.exception.util.LocalizedFormats",
      "org.apache.commons.math4.linear.AnyMatrix",
      "org.apache.commons.math4.optim.BaseOptimizer$MaxEvalCallback",
      "org.apache.commons.math4.exception.TooManyIterationsException",
      "org.apache.commons.math4.optim.linear.SimplexSolver",
      "org.apache.commons.math4.exception.NullArgumentException",
      "org.apache.commons.math4.exception.util.ExceptionContext",
      "org.apache.commons.math4.optim.linear.UnboundedSolutionException",
      "org.apache.commons.math4.exception.MaxCountExceededException",
      "org.apache.commons.math4.exception.NotStrictlyPositiveException",
      "org.apache.commons.math4.exception.util.ArgUtils",
      "org.apache.commons.math4.optim.univariate.UnivariateObjectiveFunction",
      "org.apache.commons.rng.RestorableUniformRandomProvider",
      "org.apache.commons.math4.optim.BaseMultivariateOptimizer",
      "org.apache.commons.math4.optim.BaseOptimizer$MaxIterCallback",
      "org.apache.commons.math4.util.Incrementor",
      "org.apache.commons.math4.optim.OptimizationData",
      "org.apache.commons.math4.optim.MaxIter",
      "org.apache.commons.math4.linear.RealMatrix",
      "org.apache.commons.math4.optim.MaxEval",
      "org.apache.commons.math4.exception.MathIllegalArgumentException",
      "org.apache.commons.math4.exception.util.ExceptionContextProvider",
      "org.apache.commons.math4.optim.univariate.SearchInterval",
      "org.apache.commons.rng.UniformRandomProvider",
      "org.apache.commons.math4.util.Incrementor$MaxCountExceededCallback",
      "org.apache.commons.math4.optim.linear.LinearOptimizer",
      "org.apache.commons.rng.core.source64.SplitMix64",
      "org.apache.commons.math4.optim.univariate.UnivariateOptimizer",
      "org.apache.commons.math4.exception.MathRuntimeException",
      "org.apache.commons.math4.optim.nonlinear.scalar.MultivariateOptimizer",
      "org.apache.commons.rng.core.source64.LongProvider",
      "org.apache.commons.math4.exception.MathIllegalNumberException",
      "org.apache.commons.math4.optim.PointValuePair",
      "org.apache.commons.math4.optim.linear.SimplexTableau",
      "org.apache.commons.math4.optim.linear.NoFeasibleSolutionException",
      "org.apache.commons.math4.exception.TooManyEvaluationsException",
      "org.apache.commons.math4.exception.NumberIsTooLargeException",
      "org.apache.commons.rng.core.source64.RandomLongSource",
      "org.apache.commons.math4.optim.univariate.UnivariatePointValuePair",
      "org.apache.commons.math4.optim.ConvergenceChecker",
      "org.apache.commons.math4.exception.DimensionMismatchException",
      "org.apache.commons.math4.optim.BaseOptimizer",
      "org.apache.commons.math4.optim.nonlinear.scalar.GoalType"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(BaseOptimizer_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.math4.optim.BaseOptimizer",
      "org.apache.commons.math4.optim.BaseOptimizer$MaxEvalCallback",
      "org.apache.commons.math4.optim.BaseOptimizer$MaxIterCallback",
      "org.apache.commons.math4.optim.BaseMultivariateOptimizer",
      "org.apache.commons.math4.optim.nonlinear.scalar.MultivariateOptimizer",
      "org.apache.commons.math4.optim.linear.LinearOptimizer",
      "org.apache.commons.math4.optim.linear.SimplexSolver",
      "org.apache.commons.math4.util.Incrementor",
      "org.apache.commons.math4.optim.linear.PivotSelectionRule",
      "org.apache.commons.math4.optim.univariate.UnivariateOptimizer",
      "org.apache.commons.math4.util.FastMath",
      "org.apache.commons.math4.optim.univariate.BrentOptimizer",
      "org.apache.commons.math4.exception.MathRuntimeException",
      "org.apache.commons.math4.exception.MathIllegalArgumentException",
      "org.apache.commons.math4.exception.MathIllegalNumberException",
      "org.apache.commons.math4.exception.NumberIsTooSmallException",
      "org.apache.commons.math4.exception.util.LocalizedFormats",
      "org.apache.commons.math4.exception.util.ExceptionContext",
      "org.apache.commons.math4.exception.util.ArgUtils",
      "org.apache.commons.math4.optim.MaxEval",
      "org.apache.commons.math4.exception.NotStrictlyPositiveException",
      "org.apache.commons.rng.core.BaseProvider",
      "org.apache.commons.rng.core.source64.LongProvider",
      "org.apache.commons.rng.core.source64.TwoCmres$Cmres",
      "org.apache.commons.rng.core.source64.TwoCmres$Cmres$Factory",
      "org.apache.commons.rng.core.source64.TwoCmres",
      "org.apache.commons.math4.optim.linear.SimplexTableau",
      "org.apache.commons.math4.optim.MaxIter",
      "org.apache.commons.rng.core.source32.IntProvider",
      "org.apache.commons.rng.core.source32.AbstractWell",
      "org.apache.commons.rng.core.source32.AbstractWell$IndexTable",
      "org.apache.commons.rng.core.source32.Well512a",
      "org.apache.commons.math4.optim.univariate.MultiStartUnivariateOptimizer",
      "org.apache.commons.math4.optim.nonlinear.scalar.GoalType",
      "org.apache.commons.math4.exception.MathIllegalStateException",
      "org.apache.commons.math4.exception.MaxCountExceededException",
      "org.apache.commons.math4.exception.TooManyEvaluationsException",
      "org.apache.commons.rng.core.source64.SplitMix64",
      "org.apache.commons.math4.optim.InitialGuess",
      "org.apache.commons.rng.core.source64.XorShift1024Star",
      "org.apache.commons.rng.core.source32.ISAACRandom",
      "org.apache.commons.rng.core.RandomProviderDefaultState",
      "org.apache.commons.rng.core.util.NumberFactory",
      "org.apache.commons.rng.core.source32.Well19937a",
      "org.apache.commons.math4.optim.SimpleBounds",
      "org.apache.commons.rng.core.source32.Well44497a",
      "org.apache.commons.rng.core.source32.Well44497b",
      "org.apache.commons.rng.core.source32.Well1024a",
      "org.apache.commons.rng.core.source64.MersenneTwister64",
      "org.apache.commons.rng.core.source32.JDKRandom",
      "org.apache.commons.rng.core.source32.MersenneTwister",
      "org.apache.commons.rng.core.source32.MultiplyWithCarry256",
      "org.apache.commons.rng.core.source32.Well19937c",
      "org.apache.commons.rng.core.source32.KISSRandom",
      "org.apache.commons.math4.exception.DimensionMismatchException"
    );
  }
}
